---
title: "stats 153_project"
author: "Peirang Xu"
date: "11/8/2017"
output: html_document
---
## Import data
```{r}
wholesale_training = scan("~/desktop/wholesaleamount.csv")
wholesale_training_timeseries = ts(wholesale_training, frequency = 12, start = c(1992, 1))
```

## Initial plot
```{r}
plot.ts(wholesale_training_timeseries)
```

## Least Squares Regression Estimates for Linear Time trend
```{r}
model1 = lm(wholesale_training~time(wholesale_training))
summary(model1)
plot(wholesale_training, type = "o")
abline(model1)
```

## Regression Results for Quadratic Time trend
```{r}
model2 = lm(wholesale_training ~ times(wholesale_training) + I(times(wholesale_training)^2))
summary(model2)
```

## Regression Results for the seasonal Means Model
```{r}
month. = season(wholesale_training)
model3 = lm(wholesale_training~month.)
summary(model3)
```

## Regression Results for cosine trends
```{r}
har. = harmonic(wholesale_training, 1)
model4 = lm(wholesale_training~har.)
summary(model4)
```

#ARIMA model
```{r}
library(tseries)
library(TSA)
adf.test(wholesale_training, alternative="stationary", k=0)
adf.test(diff(wholesale_training), alternative = "stationary", k=0)

acf(diff(wholesale_training))

pacf(diff(wholesale_training))

eacf(diff(wholesale_training))
```

```{r}
arima(diff(wholesale_training), order = c(1, 1, 2), include.mean = FALSE)
arima(diff(wholesale_training), order = c(2, 1, 2), include.mean = FALSE)
arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE)
arima(diff(wholesale_training), order = c(0, 1, 3), include.mean = FALSE)
```
arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE) gives the minimum AIC value.

```{r}
tsdiag(arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE))
qqnorm(residuals(arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE)));qqline(residuals(arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE)))
```

## ARCH/GARCH
```{r}
arima_wholesale = arima(diff(wholesale_training), order = c(1, 1, 3), include.mean = FALSE)
arima_wholesale_res_square = arima_wholesale$residuals^2
par(mfcol= c(3,1))
plot(arima_wholesale_res_square, main = "Squared Residuals")
acf_wholesale_squared = acf(arima_wholesale_res_square, main = "ACF Squared Residuals")
pacf_wholesale_squared = pacf(arima_wholesale_res_square, main = "PACF Squared Residuals")
```

```{r}
McLeod.Li.test(y = diff(wholesale_training))
```

```{r}
eacf(abs(arima_wholesale_res_square))
ARCH_1 = garch(arima_wholesale$residuals, order = c(0, 1))
logLik(ARCH_1)
summary(ARCH_1)

ARCH_2 = garch(arima_wholesale$residuals, order = c(0, 2))
logLik(ARCH_2)

ARCH_4 = garch(arima_wholesale$residuals, order = c(0, 4))
logLik(ARCH_3)

GARCH = garch(arima_wholesale$residuals, order = c(1, 1))
summary(GARCH)

qqnorm(residuals(ARCH_4));qqline(residuals(ARCH_4))
plot(residuals(ARCH_1), type = "h")
```
